// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABVARiz3CZ6z8FgeDZV9bAKBJj0i_i04k',
    appId: '1:796972289854:web:ebe7244ad4adeff99e666f',
    messagingSenderId: '796972289854',
    projectId: 'incremat-caregiver',
    authDomain: 'incremat-caregiver.firebaseapp.com',
    storageBucket: 'incremat-caregiver.firebasestorage.app',
    measurementId: 'G-E8WPV6LL8X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACC8GGZT6hEeVHzyVSbXXtoarZWtvpBFk',
    appId: '1:796972289854:android:484eeb922f9ef8769e666f',
    messagingSenderId: '796972289854',
    projectId: 'incremat-caregiver',
    storageBucket: 'incremat-caregiver.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8O8Gx1v6vNfH9M_FVMSQLXJm7xqZ4kts',
    appId: '1:796972289854:ios:3dfc73b385331d119e666f',
    messagingSenderId: '796972289854',
    projectId: 'incremat-caregiver',
    storageBucket: 'incremat-caregiver.firebasestorage.app',
    iosBundleId: 'com.example.incremat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8O8Gx1v6vNfH9M_FVMSQLXJm7xqZ4kts',
    appId: '1:796972289854:ios:3dfc73b385331d119e666f',
    messagingSenderId: '796972289854',
    projectId: 'incremat-caregiver',
    storageBucket: 'incremat-caregiver.firebasestorage.app',
    iosBundleId: 'com.example.incremat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABVARiz3CZ6z8FgeDZV9bAKBJj0i_i04k',
    appId: '1:796972289854:web:2860bce1cbc8a0689e666f',
    messagingSenderId: '796972289854',
    projectId: 'incremat-caregiver',
    authDomain: 'incremat-caregiver.firebaseapp.com',
    storageBucket: 'incremat-caregiver.firebasestorage.app',
    measurementId: 'G-FYV4MTLJL5',
  );
}
